# Generated by Django 6.1 on 2026-08-30 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tweet/media/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=10)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.tweet')),
            ],
        ),
    ]
